import mysql.connector
from mysql.connector import Error

#Inserir registros no banco 

try:
    con = mysql.connector.connect(host='localhost', port='3310', database='lojaok', user='root', password='c4rl0s91')

    
    inserir_produtos = """INSERT INTO Venda_Itens (ID, VENDA_ID, PRODUTO_ID, VALOR, QUANTIDADE) VALUES 
    (51,4005830,52110,"10.02","1.000"), (52,4005830,27780,"13.03","1.000"), (53,4005830,66294,"8.46","1.000"),
    (54,4005830,48947,"16.53","1.000"), (55,4006602,66197,"6.44","4.000"), (56,4006602,64231,"23.66","1.000"),
    (57,4006602,45894,"7.21","1.000"), (58,4007943,29160,"23.5","1.000"), (59,4007943,65804,"18.9","1.000"),
    (60,4007943,2040,"18.42","2.000"), (61,4009140,63731,"3.09","1.000"), (62,4009140,64122,"3.09","1.000"),
    (63,4009140,60663,"3.94","1.000"), (64,4010241,64231,"16.63","1.000"), (65,4010241,2041,"9.21","1.000"),
    (66,4010241,2040,"9.21","1.000"), (67,4010241,64353,"5.03","1.000"), (68,4010244,64231,"33.26","2.000"),
    (69,4010256,64231,"16.63","1.000"), (70,4010257,64231,"16.63","1.000"), (71,4011062,64231,"16.63","1.000"),
    (72,4011062,2156,"9.21","1.000"), (73,4013258,64231,"16.63","1.000"), (74,4014604,706,"9.4","1.000"),
    (75,4014604,707,"9.4","1.000"), (76,4019409,14243,"23.42","24.000"), (77,4020602,65720,"11.1","3.000"),
    (78,4024205,14243,"23.42","24.000"), (79,4026958,29160,"23.5","1.000"), (80,4030567,54669,"12.15","1.000"),
    (81,4030567,60211,"6.84","2.000"), (82,4030567,705,"4.71","1.000"), (83,4030567,5663,"11.31","1.000"),
    (84,4030567,14610,"7.12","1.000"), (85,4030567,2475,"15.28","12.000"), (86,4030567,2156,"9.21","1.000"),
    (87,4030567,66197,"3.22","2.000")"""

    
    cursor = con.cursor()
    cursor.execute(inserir_produtos)
    con.commit()
    print(cursor.rowcount, "Registros adicionados a tabela!")

except Error as erro:
    print("Falha ao inserir dados no SQL: {}".format(erro))
finally:
    if (con.is_connected()):
        cursor.close()
        con.close()
        print("Conex√£o ao MySQL finalizada")
